// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpJfhDA-3shkY3ob1a5_VWIcAvft6LQo',
    appId: '1:233368775196:web:251682a44de26340384dd9',
    messagingSenderId: '233368775196',
    projectId: 'chat-app-v2-edc66',
    authDomain: 'chat-app-v2-edc66.firebaseapp.com',
    storageBucket: 'chat-app-v2-edc66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-JNgRzi3KRKFq6418RDn19Zn7B0luUw',
    appId: '1:233368775196:android:74ea103a9fe305a4384dd9',
    messagingSenderId: '233368775196',
    projectId: 'chat-app-v2-edc66',
    storageBucket: 'chat-app-v2-edc66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyK0lFrqbkasDeMmhi_KZpkODJECxD5C0',
    appId: '1:233368775196:ios:23848e8d25ab6d8a384dd9',
    messagingSenderId: '233368775196',
    projectId: 'chat-app-v2-edc66',
    storageBucket: 'chat-app-v2-edc66.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
